# Generated by Django 5.0.2 on 2024-03-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouanis', '0003_expediteur_age_expediteur_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandeannonce',
            old_name='destinataire',
            new_name='voyageur',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='description',
        ),
        migrations.AddField(
            model_name='demandedecomptevoyageur',
            name='photos_passeport',
            field=models.FileField(default='default_value', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='poids_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='prix_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
