# Generated by Django 5.0.2 on 2024-05-27 13:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ouanis', '0004_rename_destinataire_demandeannonce_voyageur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_poids', models.FloatField(blank=True, null=True)),
                ('to_poids', models.FloatField(blank=True, null=True)),
                ('prix', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='demandecourier',
            name='demande_annonce',
        ),
        migrations.AlterModelOptions(
            name='expediteur',
            options={'verbose_name': 'Expediteur', 'verbose_name_plural': 'Expediteurs'},
        ),
        migrations.AlterModelManagers(
            name='expediteur',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='voyageur',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='prix_unit',
        ),
        migrations.RemoveField(
            model_name='demandeannonce',
            name='message',
        ),
        migrations.RemoveField(
            model_name='demandeannonce',
            name='voyageur',
        ),
        migrations.RemoveField(
            model_name='expediteur',
            name='age',
        ),
        migrations.RemoveField(
            model_name='expediteur',
            name='mot_de_passe',
        ),
        migrations.RemoveField(
            model_name='expediteur',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='expediteur',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='voyageur',
            name='age',
        ),
        migrations.RemoveField(
            model_name='voyageur',
            name='mot_de_passe',
        ),
        migrations.RemoveField(
            model_name='voyageur',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='voyageur',
            name='prenom',
        ),
        migrations.AddField(
            model_name='demandeannonce',
            name='poids',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandedecomptevoyageur',
            name='adresse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='demandedecomptevoyageur',
            name='numero_passeport',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expediteur',
            name='adresse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expediteur',
            name='date_de_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediteur',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='expediteur',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='expediteur',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='%(class)s_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='expediteur',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='expediteur',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='expediteur',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='expediteur',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='expediteur',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='expediteur',
            name='password',
            field=models.CharField(default=0, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expediteur',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='expediteur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='%(class)s_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='expediteur',
            name='username',
            field=models.CharField(default=1, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voyageur',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='voyageur',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='voyageur',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='%(class)s_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='voyageur',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='voyageur',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='voyageur',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='voyageur',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='voyageur',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='voyageur',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voyageur',
            name='photos_passeport',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='voyageur',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='voyageur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='%(class)s_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='voyageur',
            name='username',
            field=models.CharField(default=1, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annonce',
            name='createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='ouanis.voyageur'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='lieu_depart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='demandeannonce',
            name='annonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='ouanis.annonce'),
        ),
        migrations.AlterField(
            model_name='demandedecomptevoyageur',
            name='photos_passeport',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='expediteur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='expediteur',
            name='numero_telephone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='voyageur',
            name='adresse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='voyageur',
            name='date_de_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voyageur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='voyageur',
            name='numero_passeport',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='voyageur',
            name='numero_telephone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='AnnoncePalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouanis.annonce')),
                ('palier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouanis.palier')),
            ],
        ),
        migrations.CreateModel(
            name='AnnonceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouanis.annonce')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouanis.tag')),
            ],
        ),
        migrations.DeleteModel(
            name='DemandeColis',
        ),
        migrations.DeleteModel(
            name='DemandeCourier',
        ),
    ]
