export const conditions = [
    "No shooes",
    "No shirt",
    "No service",
    "No loud music",
    "No littering",
    "No running",
    "No swimming",
    "No skateboarding",
    "No camping",
    "No fishing",
    "No weapons",
    "No alcohol",
    "No drugs",
    "No gambling",
    "No fireworks",
    "No vandalism",
    "No ryad",
    "No malik",
    "No patafixe",
    "No trespassing",
    "No open flames",
    "No drones",
    "No entry",
    "No pets",
    "No smoking",
    "No food or drinks",
    "No photography",
    "No cell phones",
    "No loitering",
    "No soliciting",
    "No parking"
];

const sortedConditions = conditions.sort();
